# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-13 11:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0002_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='yoc3',
            field=models.IntegerField(default='2000'),
        ),
    ]
